[package]
name = "sml-symbol-kind"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
doctest = false
test = false

[dependencies]
sml-namespace = { path = "../sml-namespace" }
sml-statics-types = { path = "../sml-statics-types" }

[features]
sync = ["sml-statics-types/sync"]
