[package]
name = "millet-ls"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
crossbeam-channel = "0.4"
lsp-types = "0.74"
serde = "1.0"
serde_json = "1.0"
